name: Build iOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build MobileGlues
        run: |
          cd MobileGlues-cpp
          wget -q https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake
          cmake -B build \
            -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake \
            -DSTATICLIB=OFF \
            -DMACOS=ON \
            -DPLATFORM=OS64 \
            -DCMAKE_C_FLAGS=-Wno-error=implicit-function-declaration
          cmake --build build --config RelWithDebInfo --target mobileglues
          codesign -s - build/libmobileglues.dylib

      - name: Locate and rename .dylib
        run: |
          mkdir -p artifacts
          cp MobileGlues-cpp/build/libmobileglues.dylib artifacts/iOS_mobileglues.dylib

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: mobileglues-ios
          path: artifacts/
          archive: false
